# Generated by Django 5.1 on 2024-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('dr', 'draft'), ('pb', 'published')], max_length=2, null=True),
        ),
    ]
